
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

easy_admin_bundle:
    resource: "@BackendBundle/Controller/Admin/AdminController.php"
    type:     annotation
    prefix:   /log_back_end
    
backoffice:
    resource: '@BackendBundle/Controller/'
    type:     annotation
    prefix:   /log_back_end

frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /


_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"


#fos_js_routing:
    #resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user:
    resource: "@FrontendBundle/Resources/config/all.yml"

gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"

fos_user_profile_admin:
   path:     /log_back_end/profil
   defaults: { _controller: FOSUserBundle:Profile:show }

logout_user:
    pattern:  /logoutUser
    defaults: { _controller: FrontendBundle:User:logout }
    
admin_login:
    pattern:  /log_back_end/login
    defaults: { _controller: BackendBundle:Security:login }

admin_login_check:
    pattern:  /log_back_end/login_check
    defaults: { _controller: BackendBundle:Security:log_back_end }

admin_logout:
    pattern:  /log_back_end/logout
    defaults: { _controller: FOSUserBundle:Security:logout }

