# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
     qr_directory: '%kernel.root_dir%/../web/uploads/commandes'

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    frontend.form.registration:
        class: FrontendBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    frontend.form.profile:
            class: FrontendBundle\Form\EditProfileType
            tags:
                - { name: form.type, alias: app_user_profile }
    custom_user_manager:
            class: FrontendBundle\Doctrine\CustomUserManager
            arguments: [@security.encoder_factory, @fos_user.util.username_canonicalizer, @fos_user.util.email_canonicalizer, @fos_user.entity_manager, WebBundle\Entity\Utilisateurs]
    app.form.something:
      class: BackendBundle\Form\ProduitType
      arguments: ['@security.token_storage','@doctrine.orm.entity_manager']
      tags:
        - { name: form.type }
    app.security.access_denied_handler:
      class: WebBundle\Security\AccessDeniedHandler
    app.user_locale_listener:
      class: BackendBundle\EventListener\UserLocaleListener
      arguments: ['@security.context','@router']
    app.twig_extension:
      class: FrontendBundle\Twig\AppExtension
      public: false
      tags:
        - { name: twig.extension }

    app.locale_listener:
      class: FrontendBundle\EventSubscriber\LocaleSubscriber
      arguments: ['%kernel.default_locale%','%locale%']
      tags:
        - { name: kernel.event_subscriber }
    redirect.after.login:
        class: WebBundle\Services\AfterLoginRedirection
        arguments: ['@router']
    redirect.after.logout:
        class: WebBundle\Services\AfterLogoutRedirection
        arguments: ['@router']
    dpolac.twig_lambda.extension:
        class: DPolac\TwigLambda\LambdaExtension
        tags: [ { name: twig.extension } ]


