<?php

namespace WebBundle\Repository;

/**
 * CommandesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandesRepository extends \Doctrine\ORM\EntityRepository
{
    public function GetCommandeByPays($pays)
    {

        $query=$this->createQueryBuilder('c')
            ->leftJoin("c.pays", "py")
            ->where('py = :pays')
            ->setParameter('pays', $pays)
            ->orderBy('c.id','DESC');


        return $query->getQuery()->getResult();
    }
    public function GetCommandeByStation($station)
    {

        $query=$this->createQueryBuilder('c')
            ->leftJoin("c.station", "s")
            ->where('s = :station')
            ->setParameter('station', $station)
            ->orderBy('c.id','DESC');


        return $query->getQuery()->getResult();
    }

    public function getCommande($id)
    {

        $query=$this->createQueryBuilder('c')
            ->leftJoin("c.station", "s")
            ->leftJoin("c.utilisateur", "u")
            ->leftJoin("s.gerant", "g")
            ->leftJoin("c.pays", "p")
            ->where('c.id = :id')
            ->andWhere('g.roles LIKE :roles')
            ->setParameter('roles', '%ROLE_GERANT%')
            ->setParameter('id', $id);
        return $query->getQuery()->getOneOrNullResult();
    }
    public function nombreCommande()
    {
        $now = new \DateTime();
        $qb = $this->createQueryBuilder('c')
            ->Select('COUNT(c)')
            ->where('c.created_at >= :now')
            ->setParameter('now', $now->format('Y-m-d 00:00:00'));
        return $qb->getQuery()->getSingleScalarResult();
    }


    public function byFacture($utilisateur, $commande = null)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.utilisateur = :utilisateur')
            ->andWhere('u.valider = 1')
            ->andWhere('u.reference != 0')
            ->orderBy('u.id')
            ->setParameter('utilisateur', $utilisateur);

        if ($commande) {
            $qb = $qb->andWhere("u.id = :commande")->setParameter("commande", $commande);
            return $qb->getQuery()->getSingleResult();
        } else {
            return $qb->getQuery()->getResult();
        }

    }

}
