<?php

namespace WebBundle\Repository;

/**
 * CouleurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouleurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getcouleurByProduit($produit_id)
    {
        $q = $this->createQueryBuilder('c')
            ->addSelect("p,s")
            ->leftJoin("c.produit","p")
            ->leftJoin("c.sizes","s")
            ->where("p.id = :produit_id")
            ->setParameter("produit_id",$produit_id);


        $q = $q->getQuery();
        return $q->getResult();
    }
}
