<?php

namespace WebBundle\Repository;

/**
 * CouponRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponRepository extends \Doctrine\ORM\EntityRepository
{
    public  function getCouponByCountry($pays,$search){
        $q=$this->createQueryBuilder('c')
            ->select('c,p')
            ->leftJoin('c.pays','p')
            ->where('c.pays = :pays')
            ->andWhere('c.is_deleted = false')
            ->setParameter('pays', $pays)
            ->orderBy('c.id','DESC');


        if($search !=""){
            $q  ->andWhere('c.code like :search')
                ->setParameter('search', '%'.$search.'%');
        }


        return $q->getQuery()->getArrayResult();
    }
}
