<?php

namespace WebBundle\Repository;

/**
 * FavorisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavorisRepository extends \Doctrine\ORM\EntityRepository
{
    public function getfavorisByUser($user_id)
    {
        $q = $this->createQueryBuilder('f')
            ->addSelect("u,p,sub")
            ->leftJoin("f.utilisateur","u")
            ->leftJoin("f.produit","p")
            ->leftJoin("p.sous_categorie","sub")
            ->where("u.id = :user_id")
            ->setParameter("user_id",$user_id);
            

        $q = $q->getQuery();
        return $q->getResult();
    }
}
