<?php

namespace WebBundle\Repository;

/**
 * SizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SizeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSizeByProduit($id)
    {
        $q = $this->createQueryBuilder('s')
            ->leftJoin("s.produit","p")
            ->where("p.id = :produit_id")
            ->andWhere("s.quantite >0")
            ->setParameter("produit_id",$id)
            ->groupBy('s.libelle');
        $q = $q->getQuery();
        return $q->getResult();
    }
    public function getSizeByProduitCouleur($couleur,$produit)
    {
        $q = $this->createQueryBuilder('s')
            ->leftJoin("s.produit","p")
            ->leftJoin("s.couleur","c")
            ->where("p.id = :produit_id")
            ->andWhere("c.id = :couleur_id")
            ->andWhere("s.quantite > 0")
            ->setParameter("produit_id",$produit)
            ->setParameter("couleur_id",$couleur);
        $q = $q->getQuery();

        return $q->getResult();
    }
}
