<?php

namespace WebBundle\Repository;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getStationByPays($pays,$search)
    {
      $q=$this->createQueryBuilder('s')
          ->select('s,g,z')
          ->leftJoin("s.pays", "p")
          ->leftJoin("s.zone", "z")
          ->leftJoin("s.gerant", "g")
          ->where('s.pays = :pays')
          ->andWhere('s.isDeleted = false')
          ->setParameter('pays', $pays)
          ->orderBy('s.id','DESC');
            if($search !=""){
                $q  ->andWhere('s.nom like :search')
                    ->setParameter('search', '%'.$search.'%');

            }

        return $q->getQuery()->getArrayResult();

    }
}
