<?php

namespace WebBundle\Repository;

/**
 * CategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneRepository extends \Doctrine\ORM\EntityRepository
{
    public function getZoneByPays($pays,$search)
    {
      $q=$this->createQueryBuilder('z')
          ->select('z,p')
          ->leftJoin("z.pays", "p")
          ->where('z.pays = :pays')
          ->andWhere('z.isDeleted = false')
          ->setParameter('pays', $pays)
          ->orderBy('z.id','DESC');
            if($search !=""){
                $q  ->andWhere('z.nom like :search')
                    ->setParameter('search', '%'.$search.'%');

            }

        return $q->getQuery()->getArrayResult();

    }
}
