<?php

namespace Proxies\__CG__\WebBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Commandes extends \WebBundle\Entity\Commandes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'id', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'utilisateur', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'valider', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'created_at', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'reference', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'uid', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'pays', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'station', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'coupon', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'date_reservation', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'date_reception', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'periode_reception', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'date_annulation', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'statutcommande', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'statutpayement', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'remboursement', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'prix', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'adresselivraison', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'payzen_response', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'statut_commande_to_string', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'statut_commande_css_class', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'statut_payement_to_string', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'statut_payement_css_class', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'remboursement_to_string', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'remboursement_css_class', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'periode_to_string'];
        }

        return ['__isInitialized__', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'id', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'utilisateur', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'valider', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'created_at', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'reference', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'uid', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'pays', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'station', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'coupon', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'date_reservation', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'date_reception', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'periode_reception', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'date_annulation', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'statutcommande', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'statutpayement', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'remboursement', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'prix', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'adresselivraison', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'payzen_response', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'statut_commande_to_string', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'statut_commande_css_class', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'statut_payement_to_string', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'statut_payement_css_class', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'remboursement_to_string', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'remboursement_css_class', '' . "\0" . 'WebBundle\\Entity\\Commandes' . "\0" . 'periode_to_string'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Commandes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getStatutCommandeToString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatutCommandeToString', []);

        return parent::getStatutCommandeToString();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusCommandeCssClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusCommandeCssClass', []);

        return parent::getStatusCommandeCssClass();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatutPayementToString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatutPayementToString', []);

        return parent::getStatutPayementToString();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusPayementCssClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusPayementCssClass', []);

        return parent::getStatusPayementCssClass();
    }

    /**
     * {@inheritDoc}
     */
    public function getRemboursementToString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemboursementToString', []);

        return parent::getRemboursementToString();
    }

    /**
     * {@inheritDoc}
     */
    public function getRemboursementCssClass()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemboursementCssClass', []);

        return parent::getRemboursementCssClass();
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodeToString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodeToString', []);

        return parent::getPeriodeToString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCoupon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoupon', []);

        return parent::getCoupon();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoupon($coupon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoupon', [$coupon]);

        return parent::setCoupon($coupon);
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresselivraison(\WebBundle\Entity\UtilisateursAdresses $adresselivraison)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresselivraison', [$adresselivraison]);

        return parent::setAdresselivraison($adresselivraison);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresselivraison()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresselivraison', []);

        return parent::getAdresselivraison();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setValider($valider)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValider', [$valider]);

        return parent::setValider($valider);
    }

    /**
     * {@inheritDoc}
     */
    public function getValider()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValider', []);

        return parent::getValider();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setReference($reference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReference', [$reference]);

        return parent::setReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function getReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReference', []);

        return parent::getReference();
    }

    /**
     * {@inheritDoc}
     */
    public function getPays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPays', []);

        return parent::getPays();
    }

    /**
     * {@inheritDoc}
     */
    public function setPays($pays)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPays', [$pays]);

        return parent::setPays($pays);
    }

    /**
     * {@inheritDoc}
     */
    public function getStation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStation', []);

        return parent::getStation();
    }

    /**
     * {@inheritDoc}
     */
    public function setStation(\WebBundle\Entity\Station $station)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStation', [$station]);

        return parent::setStation($station);
    }

    /**
     * {@inheritDoc}
     */
    public function setCommande($commande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommande', [$commande]);

        return parent::setCommande($commande);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommande', []);

        return parent::getCommande();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilisateur(\WebBundle\Entity\Utilisateurs $utilisateur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilisateur', [$utilisateur]);

        return parent::setUtilisateur($utilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilisateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilisateur', []);

        return parent::getUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateclient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateclient', []);

        return parent::getDateclient();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateReservation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateReservation', []);

        return parent::getDateReservation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateReservation($date_reservation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateReservation', [$date_reservation]);

        return parent::setDateReservation($date_reservation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateReception()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateReception', []);

        return parent::getDateReception();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateReception($date_reception)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateReception', [$date_reception]);

        return parent::setDateReception($date_reception);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriodeReception()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriodeReception', []);

        return parent::getPeriodeReception();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriodeReception($periode_reception)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriodeReception', [$periode_reception]);

        return parent::setPeriodeReception($periode_reception);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAnnulation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAnnulation', []);

        return parent::getDateAnnulation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAnnulation($date_annulation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAnnulation', [$date_annulation]);

        return parent::setDateAnnulation($date_annulation);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatutcommande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatutcommande', []);

        return parent::getStatutcommande();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatutcommande($statutcommande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatutcommande', [$statutcommande]);

        return parent::setStatutcommande($statutcommande);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatutpayement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatutpayement', []);

        return parent::getStatutpayement();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatutpayement($statutpayement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatutpayement', [$statutpayement]);

        return parent::setStatutpayement($statutpayement);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemboursement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemboursement', []);

        return parent::getRemboursement();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemboursement($remboursement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemboursement', [$remboursement]);

        return parent::setRemboursement($remboursement);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayzenResponse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayzenResponse', []);

        return parent::getPayzenResponse();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayzenResponse($payzen_response)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayzenResponse', [$payzen_response]);

        return parent::setPayzenResponse($payzen_response);
    }

    /**
     * {@inheritDoc}
     */
    public function getUid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUid', []);

        return parent::getUid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUid($uid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUid', [$uid]);

        return parent::setUid($uid);
    }

}
