<?php

namespace Proxies\__CG__\WebBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Coupon extends \WebBundle\Entity\Coupon implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'id', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'code', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'montant', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'pourcentage', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'nbrcoupon', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'is_nbrcoupon', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'pays', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'commandes', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'is_active', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'is_deleted', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'type', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'type_to_string'];
        }

        return ['__isInitialized__', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'id', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'code', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'montant', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'pourcentage', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'nbrcoupon', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'is_nbrcoupon', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'pays', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'commandes', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'is_active', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'is_deleted', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'type', '' . "\0" . 'WebBundle\\Entity\\Coupon' . "\0" . 'type_to_string'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Coupon $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getTypeToString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeToString', []);

        return parent::getTypeToString();
    }

    /**
     * {@inheritDoc}
     */
    public function getPourcentage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPourcentage', []);

        return parent::getPourcentage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPourcentage($pourcentage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPourcentage', [$pourcentage]);

        return parent::setPourcentage($pourcentage);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrcoupon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrcoupon', []);

        return parent::getNbrcoupon();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrcoupon($nbrcoupon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrcoupon', [$nbrcoupon]);

        return parent::setNbrcoupon($nbrcoupon);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommandes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommandes', []);

        return parent::getCommandes();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommande(\WebBundle\Entity\Commandes $commande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommande', [$commande]);

        return parent::addCommande($commande);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommandes(\WebBundle\Entity\Commandes $commande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommandes', [$commande]);

        return parent::removeCommandes($commande);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontant($montant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontant', [$montant]);

        return parent::setMontant($montant);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontant', []);

        return parent::getMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function getPays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPays', []);

        return parent::getPays();
    }

    /**
     * {@inheritDoc}
     */
    public function setPays(\WebBundle\Entity\Pays $pays)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPays', [$pays]);

        return parent::setPays($pays);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsNbrcoupon($isNbrcoupon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsNbrcoupon', [$isNbrcoupon]);

        return parent::setIsNbrcoupon($isNbrcoupon);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsNbrcoupon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsNbrcoupon', []);

        return parent::getIsNbrcoupon();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', []);

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDeleted($isDeleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDeleted', [$isDeleted]);

        return parent::setIsDeleted($isDeleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDeleted', []);

        return parent::getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommande(\WebBundle\Entity\Commandes $commande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommande', [$commande]);

        return parent::removeCommande($commande);
    }

}
